# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 반상열 / SANGYEOL BAN
title: Hallym University Student
email: qkstkdduf309@naver.com
# email_title: Email (Email title override)
phone: 01091798552
# phone_title: Phone (Phone title override)
website: http://34.64.211.106:8080/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  Upflavor
instagram_username: gnasloey_b

# Additional icon links
#additional_links:
#- title: Link name
 # icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
 # url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: ![KakaoTalk_20221027_032750956](https://user-images.githubusercontent.com/115774445/198115346-79eaf934-5c07-4baf-b9a4-48a6a41bd456.jpg)
about_content: | # this will include new lines to allow paragraphs
 Hi! My name is SangYeol, My major is Bigdata, Department of Software.<br>
 I want to be a web developer So I chose this major. <br>
 It is very difficult to learn programming languages now, but it is so much fun that I am thinking of studying hard <br>
 Thank you so much for the opportunity to study!!!


content:
  - title: Project  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Let's fill it up
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: https://www.hallym.ac.kr/
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          I haven't done the project yet. I'll try to fill it up
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Capstone Design
        sub_title: Hallym Polytechnic University
        caption: oct 2020 - dec 2020 
        link: Link to company (optional)
        quote: >
          a previous school competition
        description: | # this will include new lines to allow paragraphs
          Use the sensor to calculate the current humidity and Adjust the strength of the wind so that the laundry can be dried well
  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Hallym University
        sub_title: Department of Software
        caption: 2017 - present
        quote: >
          The big data major curriculum provides a way to effectively store and manage large amounts of data and the subjects required to process them with high performance.
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Please visit my Instagram <br>
      You'll get to know me a little more<br>
      I like traveling. If you like traveling, it will be very interesting!! <br>
      my skills : Arduino, Python, Linux

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
